---
- name: uclalib_dspace.yml
  become: yes
  become_method: sudo
  hosts: all

  vars_files:
    - [ "vars/travis-builds/{{ travischeck }}", "vars/dspace_vars_private.yml" ]
    - "vars/dspace_vars_open.yml"

  # Dependencies:
  # ANXS/PostgreSQL role (https://github.com/ANXS/postgresql)

  vars:
    java_package: java-1.8.0-openjdk-devel.x86_64
    iptables_allowed_input_rules:
      - src_ip: 164.67.0.0/16
        dest_port: 80,8081,8082
        protocol: tcp
    env: 'test'
    handle_version: 8.1.1
    postgresql_version: 9.5
    postgresql_encoding: 'UTF-8'
    postgresql_locale: 'en_US.UTF-8'
    postgresql_ctype: 'en_US.UTF-8'
    postgresql_admin_user: "postgres"
    postgresql_default_auth_method: "md5"
    postgresql_service_enabled: true
    postgresql_pg_hba_default:
      - { type: local, database: all, user: '{{ postgresql_admin_user }}', address: '', method: trust, comment: 'PostgreSQL admin user' }
      - { type: local, database: all, user: all, address: '', method: trust, comment: 'Unix socket connections' }
      - { type: host, database: all, user: all, address: '127.0.0.1/32', method: trust, comment: 'IPv4 local connections' }
    postgresql_pg_hba_passwd_hosts:
      - t-w-dspace01.library.ucla.edu
      - p-w-dspace01.library.ucla.edu
    postgresql_listen_addresses:
      - "*"

    # create a postgresql user for dspace
    postgresql_users:
      - name: "{{ postgres_build['test']['dataden']['user']['username'] }}"
        pass: "{{ postgres_build['test']['dataden']['user']['password'] }}"
        encrypted: yes
      - name: "{{ postgres_build['test']['vsim']['user']['username'] }}"
        pass: "{{ postgres_build['test']['vsim']['user']['password'] }}"
        encrypted: yes
      - name: "{{ postgres_build['prod']['dataden']['user']['username'] }}"
        pass: "{{ postgres_build['prod']['dataden']['user']['password'] }}"
        encrypted: yes
      - name: "{{ postgres_build['prod']['vsim']['user']['username'] }}"
        pass: "{{ postgres_build['prod']['vsim']['user']['password'] }}"
        encrypted: yes

    # create a database for dspace
    postgresql_databases:
      - name: "{{ postgres_build['test']['dataden']['dbname'] }}"
        owner: "{{ postgres_build['test']['dataden']['user']['username'] }}"
        encoding: 'UTF-8'
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
      - name: "{{ postgres_build['test']['vsim']['dbname'] }}"
        owner: "{{ postgres_build['test']['vsim']['user']['username'] }}"
        encoding: 'UTF-8'
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
      - name: "{{ postgres_build['prod']['dataden']['dbname'] }}"
        owner: "{{ postgres_build['prod']['dataden']['user']['username'] }}"
        encoding: 'UTF-8'
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'
      - name: "{{ postgres_build['prod']['vsim']['dbname'] }}"
        owner: "{{ postgres_build['prod']['vsim']['user']['username'] }}"
        encoding: 'UTF-8'
        lc_collate: 'en_US.UTF-8'
        lc_ctype: 'en_US.UTF-8'

    # OPTIONAL: you can specify database extensions here (like pgcrypto, which is required for DSapce 6)
    postgresql_database_extensions:
      - db: "{{ postgres_build['test']['dataden']['dbname'] }}"
        extensions:
          - pgcrypto
      - db: "{{ postgres_build['test']['vsim']['dbname'] }}"
        extensions:
          - pgcrypto
      - db: "{{ postgres_build['prod']['dataden']['dbname'] }}"
        extensions:
          - pgcrypto
      - db: "{{ postgres_build['prod']['vsim']['dbname'] }}"
        extensions:
          - pgcrypto

    # database privileges for the dspace user
    postgresql_user_privileges:
      - name: "{{ postgres_build['test']['dataden']['user']['username'] }}"
        db: "{{ postgres_build['test']['dataden']['dbname'] }}"
        priv: "ALL"
        role_attr_flags: "CREATEDB"
      - name: "{{ postgres_build['test']['vsim']['user']['username'] }}"
        db: "{{ postgres_build['test']['vsim']['dbname'] }}"
        priv: "ALL"
        role_attr_flags: "CREATEDB"
      - name: "{{ postgres_build['prod']['dataden']['user']['username'] }}"
        db: "{{ postgres_build['prod']['dataden']['dbname'] }}"
        priv: "ALL"
        role_attr_flags: "CREATEDB"
      - name: "{{ postgres_build['prod']['vsim']['user']['username'] }}"
        db: "{{ postgres_build['prod']['vsim']['dbname'] }}"
        priv: "ALL"
        role_attr_flags: "CREATEDB"

  roles:
    - { role: uclalib_role_java }
    - { role: uclalib_role_vim }
    - { role: uclalib_role_imagemagick }
    - { role: uclalib_role_clamav }
    - { role: uclalib_role_java_maven }
    - { role: uclalib_role_java_ant }
    - { role: uclalib_role_git }
    - { role: uclalib_role_postgres, when: ansible_virtualization_type != "VMware" }
    - { role: uclalib_role_apache }
    - { role: uclalib_role_tomcat }
    - { role: uclalib_role_dspace, 
              dspace_git_repo: "{{ dspace[env].vsim.dspace_git_repo }}",
              dspace_git_branch: "{{ dspace[env].vsim.dspace_git_branch }}",
              dspace_env_build_name: "{{ dspace[env].vsim.dspace_env_build_name }}",
              dspace_name: "{{ dspace[env].vsim.dspace_name }}",
              dspace_assetstore_dir: "{{ dspace[env].vsim.dspace_assetstore_dir }}",
              dspace_hostname: "{{ dspace[env].vsim.dspace_hostname }}",
              dspace_baseUrl: "{{ dspace[env].vsim.dspace_baseUrl }}",
              dspace_localUrl: "{{ dspace[env].vsim.dspace_localUrl }}",
              dspace_ui: "{{ dspace[env].vsim.dspace_ui }}",
              dspace_solr_server: "{{ dspace[env].vsim.dspace_solr_server }}",
              dspace_default_language: "{{ dspace[env].vsim.dspace_default_language }}",
              dspace_mail_from_address: "{{ dspace[env].vsim.dspace_mail_from_address }}",
              dspace_mail_feedback_recipient: "{{ dspace[env].vsim.dspace_mail_feedback_recipient }}",
              dspace_mail_admin: "{{ dspace[env].vsim.dspace_mail_admin }}",
              dspace_mail_alert_recipient: "{{ dspace[env].vsim.dspace_mail_alert_recipient }}",
              dspace_mail_registration_notify: "{{ dspace[env].vsim.dspace_mail_registration_notify }}",
              dspace_loglevel_other: "{{ dspace[env].vsim.dspace_loglevel_other }}",
              dspace_loglevel_dspace: "{{ dspace[env].vsim.dspace_loglevel_dspace }}",
              dspace_shut_port: "{{ dspace[env].vsim.dspace_shut_port }}",
              dspace_conn_port: "{{ dspace[env].vsim.dspace_conn_port }}",
              dspace_install_dir: "{{ dspace[env].vsim.dspace_install_dir }}",
              dspace_home: "{{ dspace[env].vsim.dspace_home }}",
              dspace_base: "{{ dspace[env].vsim.dspace_base }}",
              dspace_db_server_url: "{{ dspace[env].vsim.dspace_db_server_url }}",
              dspace_service_user: "{{ dspace[env].vsim.dspace_service_user }}",
              dspace_db_poolname: "{{ dspace[env].vsim.dspace_db_poolname }}",
              dspace_db_name: "{{ postgres_build[env].vsim.dbname }}",
              dspace_db_username: "{{ postgres_build[env].vsim.user.username }}",
              dspace_db_password: "{{ postgres_build[env].vsim.user.password }}",
              dspace_xms: "{{ dspace[env].vsim.dspace_xms }}",
              dspace_xmx: "{{ dspace[env].vsim.dspace_xmx }}" }
    - { role: uclalib_role_dspace, 
              dspace_git_repo: "{{ dspace[env].dataden.dspace_git_repo }}",
              dspace_git_branch: "{{ dspace[env].dataden.dspace_git_branch }}",
              dspace_env_build_name: "{{ dspace[env].dataden.dspace_env_build_name }}",
              dspace_name: "{{ dspace[env].dataden.dspace_name }}",
              dspace_assetstore_dir: "{{ dspace[env].dataden.dspace_assetstore_dir }}",
              dspace_hostname: "{{ dspace[env].dataden.dspace_hostname }}",
              dspace_baseUrl: "{{ dspace[env].dataden.dspace_baseUrl }}",
              dspace_localUrl: "{{ dspace[env].dataden.dspace_localUrl }}",
              dspace_ui: "{{ dspace[env].dataden.dspace_ui }}",
              dspace_solr_server: "{{ dspace[env].dataden.dspace_solr_server }}",
              dspace_default_language: "{{ dspace[env].dataden.dspace_default_language }}",
              dspace_mail_from_address: "{{ dspace[env].dataden.dspace_mail_from_address }}",
              dspace_mail_feedback_recipient: "{{ dspace[env].dataden.dspace_mail_feedback_recipient }}",
              dspace_mail_admin: "{{ dspace[env].dataden.dspace_mail_admin }}",
              dspace_mail_alert_recipient: "{{ dspace[env].dataden.dspace_mail_alert_recipient }}",
              dspace_mail_registration_notify: "{{ dspace[env].dataden.dspace_mail_registration_notify }}",
              dspace_loglevel_other: "{{ dspace[env].dataden.dspace_loglevel_other }}",
              dspace_loglevel_dspace: "{{ dspace[env].dataden.dspace_loglevel_dspace }}",
              dspace_shut_port: "{{ dspace[env].dataden.dspace_shut_port }}",
              dspace_conn_port: "{{ dspace[env].dataden.dspace_conn_port }}",
              dspace_install_dir: "{{ dspace[env].dataden.dspace_install_dir }}",
              dspace_home: "{{ dspace[env].dataden.dspace_home }}",
              dspace_base: "{{ dspace[env].dataden.dspace_base }}",
              dspace_db_server_url: "{{ dspace[env].dataden.dspace_db_server_url }}",
              dspace_service_user: "{{ dspace[env].dataden.dspace_service_user }}",
              dspace_db_poolname: "{{ dspace[env].dataden.dspace_db_poolname }}",
              dspace_db_name: "{{ postgres_build[env].dataden.dbname }}",
              dspace_db_username: "{{ postgres_build[env].dataden.user.username }}",
              dspace_db_password: "{{ postgres_build[env].dataden.user.password }}",
              dspace_xms: "{{ dspace[env].dataden.dspace_xms }}",
              dspace_xmx: "{{ dspace[env].dataden.dspace_xmx }}" }
    - { role: uclalib_role_handle }
    - { role: uclalib_role_iptables, when: ansible_virtualization_type == "VMware"}